[red]
r_min = 180
g_max = 80
b_max = 80

[green]
r_max = 60
g_min = 160
b_max = 60

[blue]
r_max = 60
g_max = 60
b_min = 160

[yellow]
r_min = 180
g_min = 180
b_max = 80

[black]
r_max = 40
g_max = 40
b_max = 40

[white]
r_min = 200
g_min = 200
b_min = 200
