#mouvement
forward = ["avance", "marche", "go", "avancer", "tout droit"]
backward = ["recule", "arriere", "back", "reculer"]
turn = ["tourne", "pivote", "virage", "rotation", "tourner"]
stop = ["stop", "arrete", "halt", "stopper", "pause"]

#vision
search = ["cherche", "trouve", "scan", "detecte", "voir"]

#liaison
separator = ["et", "puis", "ensuite", "alors"]