# CONFIGURATION GENERALE PROJET PFR

[language]
langue = fr # fr or en

[simulation]
simulation_open_on_start = on # on or off

[path]
python_simulation_path = source/actuator/Simulator.py
python_vocal_interpreter_fr = source/controlMod/VoiceInterface/vocalInterpreter_FR.py
python_vocal_interpreter_en = source/controlMod/VoiceInterface/vocalInterpreter_EN.py
history_folder = history
image_folder = data

