# Mouvement
forward = ["avance", "marche", "go", "avancer", "roule","va"]
backward = ["recule", "arriere", "back", "reculer"]
turn = ["tourne", "tourner", "pivote"]
stop = ["stop", "arrete", "arreter", "halte"]
search = ["cherche", "trouve", "scan", "detecte"]

# Vision
search = ["cherche", "trouve", "scan", "detecte", "voir"]

# Séparateurs
separator = ["et", "puis", "ensuite", "alors"]

# Directions
left = ["gauche"]
right = ["droite"]

# Couleurs
red = ["rouge"]
blue = ["bleu", "bleue"]
green = ["vert", "verte"]
yellow = ["jaune"]
orange = ["orange"]
black = ["noir", "noire"]
white = ["blanc", "blanche"]

# Objets (optionnel)
cube = ["cube", "boite"]
ball = ["balle", "boule"]